### ISSUE TITLE
Schematron for newspaper year Metspointer

### ISSUE THREAD

**Issue by M3ssman** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#5]
# Description

The Pattern in Schematron-Validation in `ddb_validierung_mets-mods-ap-digitalisierte-zeitungen.sch` that checks for self-referencing Metspointers (`structMapLogical_14`) is way too general.

The current Implementation also alerts for Years which have Metspointers to their corresponding Issues / Additionals, because it is not specific enough about the expected logical structure. Having Pointers on Year-Level to subsequent OAI-Records is a obviously a must-have.

**Comment by tschleier** [comment]
Yes, the `structMapLogical_14` check is general, but it is an intended behavior as our schematron validation only validates aspects of the newspaper application profile that are relevant for the DDB and the "Zeitungsportal".

We only ingest records that describe issues or additionals - records describing other hierarchical levels (like "newspaper" or "year") are omitted. For this reason our validation is only targeted at those struct types (see [DDB Wiki](https://wiki.deutsche-digitale-bibliothek.de/display/DFD/Schematron-Validierungen+der+Fachstelle+Bibliothek#SchematronValidierungenderFachstelleBibliothek-METS/MODS-Anwendungsprofilf%C3%BCrZeitungen).

Some checks relevant to the `mets:structMap[@TYPE='LOGICAL']` are lax because we allow records describing issues and additionals without a hierarchical structure. Please see our [minimal example]( https://wiki.deutsche-digitale-bibliothek.de/x/wwGuB) and [our documentation in the DDB Wiki]( https://wiki.deutsche-digitale-bibliothek.de/x/ugGuB) (it’s currently being worked on).
We have partners that only provide records in this manner.
