### ISSUE TITLE
Inconsistency between Schematron Validation and MODS specification

### ISSUE THREAD

**Issue by M3ssman** [Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation#8]
The error `originInfo_06` of current `ddb_validierung_mets-mods-ap-digitalisierte-medien.sch` checks if the attribute `type` has value `text` (c.f. https://github.com/Deutsche-Digitale-Bibliothek/ddb-metadata-schematron-validation/blob/main/mets-mods-ap-digitalisierte-medien/ddb_validierung_mets-mods-ap-digitalisierte-medien.sch#L1435)

According to the MODS-Anwendungsprofil Kapitel 2.4.2.2.1 (c.f. https://dfg-viewer.de/fileadmin/groups/dfgviewer/MODS-Anwendungsprofil_2.3.1.pdf) there are also constellations like this valid `<mods:placeTerm type="code">` so instead it should rather look like `test="mods:placeTerm[@type=('text', 'code')]"` - or am I missing something?

Kind regards

**Comment by tschleier** [comment]
The `<mods:placeTerm type="text">` is a requirement of the DDB, because it doesn't support codes for places.
The error message with the reference to the MODS-Anwendungsprofil is misleading here - we will correct it in the next version.

Recently the Fachstelle Bibliothek has created a [DDB application profile](https://wiki.deutsche-digitale-bibliothek.de/pages/viewpage.action?pageId=19006651) which is more specific (e. g. [mods:originInfo](https://wiki.deutsche-digitale-bibliothek.de/pages/viewpage.action?pageId=69124877)).
We plan to reference it place of the MODS-Anwendungsprofil in the report and the schematron validation in the future.

With best wishes
